### Listar leads
GET https://ijbqvlwwjrxxnkbnjcay.supabase.co/rest/v1/leads?select=name,email,phone,company_name,num_employees,num_branches,has_charter_experience,main_challenge
apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlqYnF2bHd3anJ4eG5rYm5qY2F5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA1NzE3MTgsImV4cCI6MjA3NjE0NzcxOH0.E6dLC0m8_O_aCSEsM-POE9jeng0kbxbpoGKwoeNL3yg
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlqYnF2bHd3anJ4eG5rYm5qY2F5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA1NzE3MTgsImV4cCI6MjA3NjE0NzcxOH0.E6dLC0m8_O_aCSEsM-POE9jeng0kbxbpoGKwoeNL3yg

### Deletar lead pelo id
DELETE https://ijbqvlwwjrxxnkbnjcay.supabase.co/rest/v1/leads?email=eq.amb@gmail.com
apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlqYnF2bHd3anJ4eG5rYm5qY2F5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA1NzE3MTgsImV4cCI6MjA3NjE0NzcxOH0.E6dLC0m8_O_aCSEsM-POE9jeng0kbxbpoGKwoeNL3yg
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlqYnF2bHd3anJ4eG5rYm5qY2F5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA1NzE3MTgsImV4cCI6MjA3NjE0NzcxOH0.E6dLC0m8_O_aCSEsM-POE9jeng0kbxbpoGKwoeNL3yg

### Listar todas as tabelas
GET https://ijbqvlwwjrxxnkbnjcay.supabase.co/rest/v1/
apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlqYnF2bHd3anJ4eG5rYm5qY2F5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA1NzE3MTgsImV4cCI6MjA3NjE0NzcxOH0.E6dLC0m8_O_aCSEsM-POE9jeng0kbxbpoGKwoeNL3yg
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlqYnF2bHd3anJ4eG5rYm5qY2F5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA1NzE3MTgsImV4cCI6MjA3NjE0NzcxOH0.E6dLC0m8_O_aCSEsM-POE9jeng0kbxbpoGKwoeNL3yg
