### Teste endpoints conhecidos
GET https://ijbqvlwwjrxxnkbnjcay.supabase.co/rest/v1/?select=*
apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlqYnF2bHd3anJ4eG5rYm5qY2F5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA1NzE3MTgsImV4cCI6MjA3NjE0NzcxOH0.E6dLC0m8_O_aCSEsM-POE9jeng0kbxbpoGKwoeNL3yg
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlqYnF2bHd3anJ4eG5rYm5qY2F5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA1NzE3MTgsImV4cCI6MjA3NjE0NzcxOH0.E6dLC0m8_O_aCSEsM-POE9jeng0kbxbpoGKwoeNL3yg
